---
- name: "Install git"
  package:
    name: git
    state: present

- name: "Set git config"
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  become_user: "{{ linux_user_name }}"
  with_items:
    - { name: 'user.name', value: "{{ git_user_name }}" }
    - { name: 'user.email', value: "{{ git_user_email }}" }
    - { name: 'core.editor', value: vim }